apiVersion: v1
kind: Service
metadata:
  name: ves
  namespace: voltha
  labels:
    name: ves
spec:
  type: NodePort
  ports:
    - name: rest
      port: 8080
      nodePort: 32079
  selector:
    app: ves
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ves
  namespace: voltha
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: voltha
    spec:
      containers:
        - name: voltha
          image: docker-repo.dev.atl.foundry.att.com:5000/voltha-ves-agent:1
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          
          ports:
            - containerPort: 8080
              name: rest-port
          imagePullPolicy: IfNotPresent
